### ISSUE TITLE
7.7 Branch webapp problems to login

### ISSUE THREAD

**Issue by Xen00x** [sipcapture/homer7-docker#53] opened 2019-12-12 08:39 UTC
We upated Homer to 7.7 branch and find that default user and password not working. In further investigation we found what it trying to connect: http://de9.sipcapture.io
![homer-image](https://user-images.githubusercontent.com/20781071/70696081-a4614b80-1ccb-11ea-84dc-e0fe83b2d0e3.png)

**Comment by adubovikov** [comment] 2019-12-12 08:43
normaly it should go to your local API and not to the public. Let us check it

**Comment by adubovikov** [comment] 2019-12-12 17:21
can you please update and check again please ?

**Comment by lmangani** [comment] 2019-12-12 20:38
This has been fixed in both repo and docker images! 
Root cause was simply a commit too many ending up in the repository.
Thanks for bringing this to our attention!

**Closed by lmangani** 2019-12-12 20:38 UTC
