### ISSUE TITLE
Postgresql does not create homer_data

### ISSUE THREAD

**Issue by heimdull** [sipcapture/homer7-docker#58] opened 2020-01-25 16:21 UTC
using hom7-prom-all with docker-compose up -d I still had to connect to postgres  server and create the homer_data database. Is this a bug or was I doing something wrong.

**Comment by lmangani** [comment] 2020-01-25 16:36
Hi @heimdull you are using the 7.7. branch correct?

**Comment by heimdull** [comment] 2020-01-25 16:55
correct 7.7

**Comment by lmangani** [comment] 2020-01-25 17:02
What are the commands you had to run specifically? Could you make sure you pulled the latest version of the `heplify-server` container and try a fresh run? We'll need logs if it fails please.

**Comment by lmangani** [comment] 2020-01-25 19:15
I could not reproduce this personally, but I've added a couple fixes which might solve your case. The directory can be created (and should be) by either `hepflify-server` or `homer-app` during initialization. Please pull the latest containers and let us know if this is resolved - thanks for your report! :)

**Comment by heimdull** [comment] 2020-01-25 21:50
I think what you did resolved the issue. I did a git clone and docker-compose up -d on a new fresh vm and it worked this time. Still cant get Grafana to show data unless I empty HEPLIFYSERVER_PROMTARGETIP and HEPLIFYSERVER_PROMTARGETNAME but everything else is looking great now.

**Comment by lmangani** [comment] 2020-01-25 22:08
Great, thanks for confirming so. Could you open an issue for the stats separately? Closing this one!

**Closed by lmangani** 2020-01-25 22:08 UTC
